# Generated by Django 5.2.3 on 2025-06-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodieapp', '0002_category_alter_menuitem_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
