# Generated by Django 5.2.3 on 2025-06-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodieapp', '0004_alter_category_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
